### ISSUE TITLE
http agent v0.10.3 error in web worker - Failed to execute 'fetch' on 'WorkerGlobalScope': Illegal invocation

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/agent-js#540]
**Describe the bug**

I cannot bump my dependencies from `v0.10.0` to `v0.10.3` because I face following error at runtime:

```
user.ic.worker-4172512a.js:14844 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Illegal invocation
    at HttpAgent.query (user.ic.worker-4172512a.js:14844:37)
    at async caller (user.ic.worker-4172512a.js:16565:28)
```

The error origin is following [line of code](https://github.com/dfinity/agent-js/blob/f07ed959b5697f27ed360d94a140b859bbc054e0/packages/agent/src/agent/http/index.ts#L251) in `@dfinity/http`

Summarized: v0.10.3 cannot be used in a web worker

**Expected behavior**
Still being able to use the lib in a web worker as with version v0.10.0

**Comment by peterpeterparker** [comment]
Resolved by https://github.com/dfinity/agent-js/pull/527
