### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/agent-js#708]
**Is your feature request related to a problem? Please describe.**

I tried to integrate agent-js in a Supabase function which uses Deno but, build failed.

```
❯ npx supabase functions deploy cron-statuses
Version 1.30.3 is already installed
Bundling cron-statuses
Error: Error bundling function: exit status 1
file:///src/import_map.json
file:///src/index.ts
error: Uncaught (in promise) Error: Relative import path "@dfinity/agent" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v114/@dfinity/identity@0.15.5/lib/cjs/identity/delegation.d.ts"
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:312:19)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:79439)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1388039)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1862894)
    at __wbg_adapter_18 (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:146:6)
    at real (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:130:14)

Try rerunning the command with --debug to troubleshoot the error.
```

For sample code:

```
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import {Ed25519KeyIdentity} from "https://esm.sh/@dfinity/identity";

console.log("Hello from Functions!")

const key = Ed25519KeyIdentity.generate();
console.log("Key", key);

serve(async (req) => {
  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }

  console.log('LOG:', data.message);

  return new Response(
    JSON.stringify(data),
    { headers: { "Content-Type": "application/json" } },
  )
})
```

**Comment by krpeacock** [comment]
Verified still not working in Feb '24. Unfortunately, I don't think we can fix this until we replace the `borc` dependency

**Comment by peterpeterparker** [comment]
Verified today January 28. It seems to work out now!

Deployed following code in a Supbase Edge Functions which generates and identity and make an anonymous call to the IC. 

```
// Follow this setup guide to integrate the Deno language server with your editor:
// https://deno.land/manual/getting_started/setup_your_environment
// This enables autocomplete, go to definition, etc.

// Setup type definitions for built-in Supabase Runtime APIs
import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { satelliteVersion } from 'npm:@junobuild/admin'
import { AnonymousIdentity } from 'npm:@dfinity/agent'
import { Ed25519KeyIdentity } from 'npm:@dfinity/identity'

console.log("Hello from Functions!")

Deno.serve(async (req) => {
  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }

  try {
    const version = await satelliteVersion({
      satellite: {
        satelliteId: "fqotu-wqaaa-aaaal-acp3a-cai",
        identity: new AnonymousIdentity(),
      }
    });

    const key = Ed25519KeyIdentity.generate();

    const result = {
      ...data,
      version,
      key: key.getPrincipal().toText()
    }

    return new Response(
        JSON.stringify(result),
        { headers: { "Content-Type": "application/json" } },
    )
  } catch (error) {
    console.error(error);

    return new Response(
        JSON.stringify(error),
        { headers: { "Content-Type": "application/json" } },
    )
  }
})
```

Query.

```
curl --request POST 'https://.....supabase.co/functions/v1/call-canister' \
  --header 'Authorization: Bearer ...' \
  --header 'Content-Type: application/json' \
  --data '{ "name":"Functions" }'
```

Results:

```
{"message":"Hello Functions!","version":"0.0.21","key":"ma4ez-vo4t3-vjemg-czzjm-rmtrk-wi3qc-ezkwd-yu7xu-hxgj6-2j2wi-2ae"}
```

It probably now works out because Deno supports npm. Great news!
